site_name: Proyecto deferia.cr

nav:
    - Inicio: index.md
    - Identidad visual: identidad.md
    - Sobre el proyecto: sobre.md

extra_css:
  - stylesheets/extra.css

theme:
  name: material
  language: es
  palette:
    scheme: feria
  font:
    text: Nunito Sans
  logo: assets/logos/logo_blanco.svg
  favicon: assets/logos/logo_rojo.svg
  features:
    - navigation.expand
    - navigation.tabs
    - navigation.footer
    - toc.integrate

markdown_extensions:
  - footnotes
  - admonition
  - pymdownx.details
  - pymdownx.superfences 
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

repo_url: https://github.com/fabianabarca/ferias
repo_name: fabianabarca/ferias

extra:
  generator: false